# Generated by Django 3.0.5 on 2020-05-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0003_auto_20200429_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renteditem',
            options={'ordering': ('start_datetime',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renteditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='JarakAPI.Product'),
        ),
        migrations.AlterField(
            model_name='renteditem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='JarakAPI.Profile'),
        ),
    ]
