# Generated by Django 3.0.5 on 2020-05-02 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0004_auto_20200502_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renteditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='JarakAPI.Product'),
        ),
        migrations.AlterField(
            model_name='renteditem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='JarakAPI.Profile'),
        ),
    ]
