# Generated by Django 3.0.5 on 2020-05-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0004_auto_20200502_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renteditem',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='JarakAPI.Profile'),
            preserve_default=False,
        ),
    ]
