# Generated by Django 3.0.5 on 2020-05-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0005_auto_20200502_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
