# Generated by Django 3.0.5 on 2020-04-28 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0007_renteditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='renteditem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 11, 2, 57, 29599)),
        ),
    ]
