# Generated by Django 3.0.5 on 2020-04-28 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0008_auto_20200428_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renteditem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 11, 12, 50, 809845)),
        ),
    ]
