# Generated by Django 3.0.5 on 2020-05-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0008_auto_20200503_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renteditem',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
