# Generated by Django 3.0.5 on 2020-04-28 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0009_auto_20200428_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='renteditem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='renteditem',
            name='rented',
        ),
        migrations.AddField(
            model_name='profile',
            name='items_rented',
            field=models.ManyToManyField(null=True, to='JarakAPI.Product'),
        ),
        migrations.AddField(
            model_name='renteditem',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='renteditem',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 28, 12, 24, 31, 839715, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JarakAPI.Profile'),
        ),
        migrations.AlterField(
            model_name='renteditem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JarakAPI.Product'),
        ),
        migrations.AlterField(
            model_name='renteditem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JarakAPI.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JarakAPI.Location'),
        ),
    ]
