# Generated by Django 3.0.5 on 2020-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JarakAPI', '0011_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
